#!/bin/bash
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 0
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 1
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 2
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 3
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 4
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 5
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 6
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 7
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 8
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 9
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 10
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 11
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 12
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 13
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 14
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 15
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 16
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 17
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 18
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 19
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 20
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 21
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 22
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 23
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 24
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 25
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 26
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 27
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 28
python RunSimulation.py --P1 MR --P2 GR --Tau 0.0 --treefile ./Thornton_MRGRARPR.newick --Geo 50.0 --sim_num 29
